util.AddNetworkString("requestLP")

function sendLP(client,toGet)
    local query = mysql:Select("hl2_lp")
		query:Select("character_id")
		query:Select("lp_amount")
		query:Select("lp_description")
		query:WhereIn("character_id", toGet)
		query:Callback(function(result)
			print("send back lp request")
            net.Start("requestLP")
            net.WriteTable(result)
            net.Send(client)
	    end)
	query:Execute()
end

function commitLP(charID,amount,desc)
		local insertQuery = mysql:Insert("hl2_lp")
		insertQuery:Insert("character_id",charID)
		insertQuery:Insert("lp_amount", amount)
		insertQuery:Insert("lp_description", desc)
		insertQuery:Execute()	
end

net.Receive("requestLP", function(len,ply)
	print("someone requests lp table")
	local toGet = net.ReadInt(10)
	sendLP(ply,toGet)
end)