ITEM.name = "Granat"
ITEM.description = "Mały granat MK3A2 w kolorze zielonym, który eksploduje kilka sekund po rzuceniu."
ITEM.model = "models/weapons/w_grenade.mdl"
ITEM.class = "weapon_frag"
ITEM.weaponCategory = "grenade"
ITEM.classes = {CLASS_EOW}
ITEM.flag = "V"
ITEM.width = 1
ITEM.height = 1